datasets:
  coco2017:
    name: &dataset_name 'coco2017'
    type: 'cocodetect'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      val:
        dataset_id: &coco_val !join [*dataset_name, '/val']
        images: !join [*root_dir, '/val2017']
        annotations: !join [*root_dir, '/annotations/instances_val2017.json']
        annotated_only: False

models:
  teacher_model:
    name: &teacher_model_name 'retinanet_resnet50_fpn'
    params:
      pretrained: True
      progress: True
      num_classes: 91
      pretrained_backbone: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/coco2017/teacher/', *teacher_experiment, '.pt']
  student_model:
    name: &student_model_name 'custom_retinanet_resnet_fpn'
    params:
      pretrained: True
      progress: True
      num_classes: 91
      pretrained_backbone: True
      backbone:
        name: 'custom_resnet50'
        params:
          num_classes: 1000
          pretrained: True
          trainable_backbone_layers: 5
          layer1:
            type: 'Bottleneck4LargeResNet'
            bottleneck_channel: &bch 2
            compressor:
              name: 'QuantizerWrapper'
              params:
                num_bits: 8
                analysis_config:
                  mean_std_file_size: True
            decompressor:
              name: 'Dequantizer'
              params:
                num_bits: 8
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '-b', *bch, 'ch_from_', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/coco2017/bq/', *student_experiment, '.pt']

test:
  test_data_loader:
    dataset_id: *coco_val
    random_sample: False
    batch_size: 1
    num_workers: 16
    collate_fn: 'coco_collate_fn'
