datasets:
  pascal_voc:
    name: &dataset_name 'VOC2012'
    type: 'VOCSegmentation'
    root: &root_dir '~/dataset/'
    splits:
      val:
        dataset_id: &pascal_voc2012_val !join [*dataset_name, '/val']
        params:
          root: *root_dir
          image_set: 'val'
          year: '2012'
          download: False
          transforms_compose_cls: 'CustomCompose'
          transforms_params: &val_transform
            - type: 'CustomRandomResize'
              params:
                min_size: 520
                max_size: 520
            - type: 'CustomToTensor'
              params:
            - type: 'CustomNormalize'
              params:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]
      test:
        dataset_id: &pascal_voc2012_test !join [*dataset_name, '/test']
        params:
          root: *root_dir
          image_set: 'val'
          year: '2012'
          download: False
          transforms_compose_cls: 'CustomCompose'
          transforms_params: *val_transform

models:
  teacher_model:
    name: &teacher_model_name 'deeplabv3_resnet50'
    params:
      pretrained: True
      num_classes: 21
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/semantic_segmentation/teacher/', *teacher_experiment, '.pt']
  student_model:
    name: &student_model_name 'custom_deeplabv3_resnet'
    params:
      pretrained: True
      progress: True
      num_classes: 21
      pretrained_backbone: True
      backbone:
        name: 'custom_resnet50'
        params:
          num_classes: 1000
          pretrained: True
          layer1:
            type: 'Bottleneck4LargeResNet'
            bottleneck_channel: &bch 2
            compressor:
              name: 'QuantizerWrapper'
              params:
                num_bits: 8
                analysis_config:
                  mean_std_file_size: True
            decompressor:
              name: 'Dequantizer'
              params:
                num_bits: 8
    experiment: &student_experiment !join ['coco2017-', *student_model_name, '-b', *bch, 'ch_from_', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/coco2017/bq/', *student_experiment, '.pt']

test:
  test_data_loader:
    dataset_id: *pascal_voc2012_test
    random_sample: False
    batch_size: 1
    num_workers: 16
