datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    type: 'ImageFolder'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        params:
          root: !join [*root_dir, '/val']
          transform_params:
            - type: 'Resize'
              params:
                size: 256
            - type: 'CenterCrop'
              params:
                size: [224, 224]
            - type: 'ToTensor'
              params:
            - type: 'Normalize'
              params:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]

models:
  teacher_model:
    name: &teacher_model_name 'resnet50'
    params:
      num_classes: 1000
      pretrained: True
    experiment: &teacher_experiment !join [*dataset_name, '-', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/teacher/', *teacher_experiment, '.pt']
  student_model:
    name: &student_model_name 'custom_resnet50'
    params:
      bottleneck_channel: &bch 3
      bottleneck_idx: 7
      compressor:
        name: 'QuantizerWrapper'
        params:
          num_bits: 8
          analysis_config:
            mean_std_file_size: True
      decompressor:
        name: 'Dequantizer'
        params:
          num_bits: 8
      num_classes: 1000
      pretrained: True
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name, '-b', *bch, 'ch_from_', *teacher_model_name]
    ckpt: !join ['./resource/ckpt/ilsvrc2012/bq/', *student_experiment, '.pt']

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
