datasets:
  coco2017:
    name: &dataset_name 'coco2017'
    type: 'cocodetect'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      val:
        dataset_id: &coco_val !join [*dataset_name, '/val']
        images: !join [*root_dir, '/val2017']
        annotations: !join [*root_dir, '/annotations/instances_val2017.json']
        annotated_only: False

models:
  model:
    name: 'InputCompressionDetector'
    params:
      analysis_config:
        mean_std_file_size: True
      adaptive_pad_config:
        fill: 0
        padding_mode: 'constant'
        factor: 128
    compressor:
      name: 'FactorizedPriorAE'
      params:
        entropy_bottleneck_channels: 128
      ckpt: './resource/ckpt/input_compression/factorized_prior_ae_128ch-beta_0.00015625.pt'
    detector:
      name: 'retinanet_resnet50_fpn'
      params:
        pretrained: True
        progress: True
        pretrained_backbone: True
      ckpt: ''

test:
  test_data_loader:
    dataset_id: *coco_val
    random_sample: False
    batch_size: 1
    num_workers: 4
    collate_fn: 'coco_collate_fn'
