datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    type: 'ImageFolder'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        params:
          root: !join [*root_dir, '/val']
          transform_params:
            - type: 'Resize'
              params:
                size: 256
            - type: 'CenterCrop'
              params:
                size: &input_size [224, 224]
            - type: 'ToTensor'
              params:
            - type: 'Pad'
              params:
                padding: 16
                fill: 0

models:
  model:
    name: 'InputCompressionClassifier'
    params:
      post_transform_params:
        - type: 'CenterCrop'
          params:
            size: *input_size
        - type: 'Normalize'
          params:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
      analysis_config:
        mean_std_file_size: True
    compressor:
      name: 'FactorizedPriorAE'
      params:
        entropy_bottleneck_channels: 128
      ckpt: './resource/ckpt/input_compression/factorized_prior_ae_128ch-0.00015625-epoch.pt'
    classifier:
      name: &model_name 'resnet50'
      params:
        num_classes: 1000
        pretrained: True
      experiment: &experiment !join [*dataset_name, '-', *model_name]
      ckpt: !join ['./resource/ckpt/', *experiment, '.pt']

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
