datasets:
  ilsvrc2012:
    name: &dataset_name 'ilsvrc2012'
    type: 'ImageFolder'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      val:
        dataset_id: &imagenet_val !join [*dataset_name, '/val']
        params:
          root: !join [*root_dir, '/val']
          transform_params:
            - type: 'Resize'
              params:
                size: 256
            - type: 'JpegCenterCrop'
              params:
                size: [224, 224]
                jpeg_quality: 90
            - type: 'ToTensor'
              params:
            - type: 'Normalize'
              params:
                mean: [0.485, 0.456, 0.406]
                std: [0.229, 0.224, 0.225]

models:
  model:
    name: &model_name 'resnet50'
    params:
      num_classes: 1000
      pretrained: True
    ckpt: !join ['./resource/ckpt/ilsvrc2012/', *model_name, '.pt']

test:
  test_data_loader:
    dataset_id: *imagenet_val
    random_sample: False
    batch_size: 1
    num_workers: 16
