datasets:
  coco2017:
    name: &dataset_name 'coco2017'
    type: 'cocodetect'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &coco_train !join [*dataset_name, '/train']
        images: !join [*root_dir, '/train2017']
        annotations: !join [*root_dir, '/annotations/person_keypoints_train2017.json']
        annotated_only: True
        random_horizontal_flip: 0.5
      val:
        dataset_id: &coco_val !join [*dataset_name, '/val']
        images: !join [*root_dir, '/val2017']
        annotations: !join [*root_dir, '/annotations/person_keypoints_val2017.json']
        annotated_only: False

models:
  model:
    name: &student_model_name 'keypointrcnn_mobilenet_v3_large_fpn'
    params:
      pretrained: False
      progress: True
      num_classes: 2
      num_keypoints: 17
      pretrained_backbone: True
      rpn_score_thresh: 0.05
    experiment: &student_experiment !join [*dataset_name, '-', *student_model_name]
    ckpt: !join ['./coco/', *student_experiment, '.pt']

train:
  log_freq: 1000
  num_epochs: 46
  train_data_loader:
    dataset_id: *coco_train
    random_sample: True
    num_workers: 4
    batch_sampler:
      type: 'GroupedBatchSampler'
      params:
        aspect_ratio_group_factor: 3
        batch_size: 2
    collate_fn: 'coco_collate_fn'
    cache_output:
  val_data_loader:
    dataset_id: *coco_val
    random_sample: False
    batch_size: 1
    num_workers: 4
    collate_fn: 'coco_collate_fn'
  model:
    forward_proc: 'forward_batch_target'
    adaptations:
    sequential: []
    forward_hook:
      input: []
      output: []
    wrapper:
    requires_grad: True
  apex:
    requires: False
    opt_level: '01'
  optimizer:
    type: 'SGD'
    params:
      lr: 0.0025
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    type: 'MultiStepLR'
    params:
      milestones: [36, 43]
      gamma: 0.1
  criterion:
    type: 'GeneralizedCustomLoss'
    func2extract_org_loss: 'extract_org_loss_dict'
    org_term:
      factor: 1.0
    sub_terms:

test:
  test_data_loader:
    dataset_id: *coco_val
    random_sample: False
    batch_size: 1
    num_workers: 4
    collate_fn: 'coco_collate_fn'
