datasets:
  coco2017:
    name: &dataset_name 'coco2017'
    type: 'cocodetect'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &coco_train !join [*dataset_name, '/train']
        images: !join [*root_dir, '/train2017']
        annotations: !join [*root_dir, '/annotations/instances_train2017.json']
        annotated_only: True
        is_segment: True
        random_horizontal_flip: 0.5
        transforms_params:
          - type: 'CustomRandomResize'
            params:
              min_size: 260
              max_size: 1040
          - type: 'CustomRandomHorizontalFlip'
            params:
              p: 0.5
          - type: 'CustomRandomCrop'
            params:
              size: 480
          - &totensor
            type: 'CustomToTensor'
            params:
          - &normalize
            type: 'CustomNormalize'
            params:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
      val:
        dataset_id: &coco_val !join [*dataset_name, '/val']
        images: !join [*root_dir, '/val2017']
        annotations: !join [*root_dir, '/annotations/instances_val2017.json']
        annotated_only: False
        is_segment: True
        transforms_params:
          - type: 'CustomRandomResize'
            params:
              min_size: 520
              max_size: 520
          - *totensor
          - *normalize

models:
  model:
    name: 'deeplabv3_resnet50'
    params:
      pretrained: True
      progress: True
      pretrained_backbone: True
    ckpt: !join ['./edited_ckpt/deeplabv3_resnet50-ilsvrc2012.pt']

test:
  test_data_loader:
    dataset_id: *coco_val
    random_sample: False
    batch_size: 1
    num_workers: 4
    collate_fn: 'coco_seg_eval_collate_fn'
