datasets:
  coco2017:
    name: &dataset_name 'coco2017'
    type: 'cocodetect'
    root: &root_dir !join ['~/dataset/', *dataset_name]
    splits:
      train:
        dataset_id: &coco_train !join [*dataset_name, '/train']
        images: !join [*root_dir, '/train2017']
        annotations: !join [*root_dir, '/annotations/person_keypoints_train2017.json']
        annotated_only: True
        random_horizontal_flip: 0.5
      val:
        dataset_id: &coco_val !join [*dataset_name, '/val']
        images: !join [*root_dir, '/val2017']
        annotations: !join [*root_dir, '/annotations/person_keypoints_val2017.json']
        annotated_only: False

models:
  model:
    name: 'keypointrcnn_resnet50_fpn'
    params:
      pretrained: True
      progress: True
      num_classes: 2
      num_keypoints: 17
      pretrained_backbone: True
    ckpt: './resource/edited_ckpt/keypointrcnn_resnet50_fpn-deeplabv3_resnet50.pt'

test:
  test_data_loader:
    dataset_id: *coco_val
    random_sample: False
    batch_size: 1
    num_workers: 4
    collate_fn: 'coco_collate_fn'
